Repository uasoft-indonesia/badaso-sitemap-module, pull requests merged in 2021-07, with the labels that each got.

#14 [Badaso v1] Bugfix/v1/update name
  CONTRIBUTING.md
  composer.json
Labels: bugfix, dependencies

#15 [Badaso v2] Bugfix/v2/update name
  CONTRIBUTING.md
  composer.json
Labels: bugfix, dependencies

#16 Merge develop to main
  CONTRIBUTING.md
  composer.json
Labels: dependencies

#18 Prepare for 2.0.0-rc.1
  composer.json
Labels: dependencies

#19 [Badaso v1] update readme.md
  README.md
Labels: bugfix

#20 [Badaso v2] update readme.md
  README.md
Labels: bugfix

#22 [v1] update sitemap
  src/Config/badaso-sitemap.php
Labels: backend

#23 [v2] update sitemap
  src/Config/badaso-sitemap.php
Labels: backend
