Repository uasoft-indonesia/badaso-sitemap-module, pull requests merged in 2021-05, with the labels that each got.

#5 change env key name
  README.md
  src/Controllers/SitemapController.php
Labels: backend

#6 Bugfix/middleware bug
  README.md
  composer.json
  src/Middleware/CaptureRequestMiddleware.php
  src/Providers/BadasoSitemapModuleServiceProvider.php
Labels: backend, bugfix, dependencies

#7 Merge develop to main
  README.md
  composer.json
  src/Middleware/CaptureRequestMiddleware.php
  src/Providers/BadasoSitemapModuleServiceProvider.php
Labels: backend, dependencies

#8 bump version to 1.0.0.0-alpha.2
  composer.json
Labels: dependencies
